name: cricket-hcms-demo

services:
  hcms:
    image: gskorupa/cricket-hcms:latest
    container_name: hcms
    hostname: hcms
    environment:
      FOLDERS_ROOT: ./documents
      FILE_TO_WATCH: version.txt
      HCMS_SERVICE_URL: http://localhost:8081
    expose:
      - "8080"
    ports:
      - "8081:8080"
    volumes:
      - ./documents:/home/jboss/documents
    networks:
      - hcms
  
  website:
    image: gskorupa/cricket-website:latest
    container_name: website
    hostname: website
    depends_on:
      - hcms
    ports:
      - "8080:3000"
    networks:
      - hcms

networks:
  hcms:
    driver: bridge
