name: cricket-hcms-demo-dev

services:
  hcms:
    image: cricket-hcms:latest
    environment:
      FOLDERS_ROOT: ./documents
      FILE_TO_WATCH: version.txt
      HCMS_SERVICE_URL: http://localhost:8081
    expose:
      - "8080"
    ports:
      - "8081:8080"
    volumes:
      - ./documents:/home/jboss/documents
    networks:
      - hcms
  
  website:
    image: cricket-website:latest
    depends_on:
      - hcms
    ports:
      - "8080:3000"
    networks:
      - hcms

networks:
  hcms:
    driver: bridge
